### ISSUE TITLE
Error in importing examples

### ISSUE THREAD

**Issue by RJ722** [robocomp/learnbot#63]
Whenever importing an example in the IDE, the following error occurs:
```
Traceback (most recent call last):
  File "/home/deep/robocomp/components/learnbot/learnbot_dsl/learnbotCode/LearnBlock.py", line 370, in openProyect
    self.scene.setBlockDict(d[0])
  File "/home/deep/robocomp/components/learnbot/learnbot_dsl/learnbotCode/Scene.py", line 66, in setBlockDict
    visualItem = BlockItem(blockItem, self.view, self)
  File "/home/deep/robocomp/components/learnbot/learnbot_dsl/learnbotCode/VisualFuntion.py", line 38, in __init__
    self.dicTrans = parentBlock.dicTrans
AttributeError: AbstractBlockItem instance has no attribute 'dicTrans'
```

Nothing happens in the IDE itself.

**Comment by pilarbachiller** [comment]
Thank you for your message. We will update these files in a couple of days.
